# -*- coding: utf-8 -*-
"""Crop_Recommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wyXJ_w3bVrFyPwTJksAdkSU6Gza9jfGY
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

crop_recommendation_df = pd.read_csv(r'C:\Users\Prannavakhanth\Documents\Crop-Core_Tech\AI\Crop_Yield_Prediction\Crop_recommendation.csv')
crop_recommendation_df.head()

features = crop_recommendation_df[crop_recommendation_df.columns.drop("label")]
target = crop_recommendation_df["label"]

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.1, random_state=42)

model = RandomForestClassifier()
model.fit(X_train, y_train)
predictions = model.predict(X_test)

print(f"Accuracy Score: {accuracy_score(y_test, predictions): .2f}")
